/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule loginMutation.graphql
 * @generated SignedSource<<28bd84492dc934864a53b02c184f2106>>
 * @relayHash 82b2b29b319506bdf26d59b8912aabfd
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';
export type LoginUserWithAuth0LockInput = {
  identity: LoginUserWithAuth0LockInput_identity;
  access_token?: ?string;
};

export type LoginUserWithAuth0LockInput_identity = {
  userId?: ?string;
  provider?: ?string;
  connection?: ?string;
  isSocial?: ?boolean;
  expiresIn?: ?number;
};

export type loginMutationResponse = {
  user?: ?loginMutationResponse_user;
};

export type loginMutationResponse_user = {
  id: string;
};
*/


/*
mutation loginMutation(
  $input: LoginUserWithAuth0LockInput!
) {
  loginUserWithAuth0Lock(input: $input) {
    user {
      id
    }
    clientMutationId
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "LoginUserWithAuth0LockInput!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "loginMutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "LoginUserWithAuth0LockInput!"
          }
        ],
        "concreteType": "LoginUserWithAuth0LockPayload",
        "name": "loginUserWithAuth0Lock",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "User",
            "name": "user",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              }
            ],
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "clientMutationId",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Mutation"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "loginMutation",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "LoginUserWithAuth0LockInput!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "loginMutation",
    "operation": "mutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "LoginUserWithAuth0LockInput!"
          }
        ],
        "concreteType": "LoginUserWithAuth0LockPayload",
        "name": "loginUserWithAuth0Lock",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "User",
            "name": "user",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              }
            ],
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "clientMutationId",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "mutation loginMutation(\n  $input: LoginUserWithAuth0LockInput!\n) {\n  loginUserWithAuth0Lock(input: $input) {\n    user {\n      id\n    }\n    clientMutationId\n  }\n}\n"
};

module.exports = batch;
