// flow-typed signature: 28265b0e392da96a64f9d34d377f6f4d
// flow-typed version: <<STUB>>/auth0-react-lock_v^1.0.4/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auth0-react-lock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'auth0-react-lock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'auth0-react-lock/build/components/lock.component' {
  declare module.exports: any;
}

declare module 'auth0-react-lock/build/index' {
  declare module.exports: any;
}

declare module 'auth0-react-lock/coverage/Chrome 50.0.2661 (Mac OS X 10.11.5)/prettify' {
  declare module.exports: any;
}

declare module 'auth0-react-lock/coverage/Chrome 50.0.2661 (Mac OS X 10.11.5)/sorter' {
  declare module.exports: any;
}

declare module 'auth0-react-lock/env.example' {
  declare module.exports: any;
}

declare module 'auth0-react-lock/env' {
  declare module.exports: any;
}

declare module 'auth0-react-lock/src/components/lock.component' {
  declare module.exports: any;
}

declare module 'auth0-react-lock/src/index' {
  declare module.exports: any;
}

declare module 'auth0-react-lock/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'auth0-react-lock/build/components/lock.component.js' {
  declare module.exports: $Exports<'auth0-react-lock/build/components/lock.component'>;
}
declare module 'auth0-react-lock/build/index.js' {
  declare module.exports: $Exports<'auth0-react-lock/build/index'>;
}
declare module 'auth0-react-lock/coverage/Chrome 50.0.2661 (Mac OS X 10.11.5)/prettify.js' {
  declare module.exports: $Exports<'auth0-react-lock/coverage/Chrome 50.0.2661 (Mac OS X 10.11.5)/prettify'>;
}
declare module 'auth0-react-lock/coverage/Chrome 50.0.2661 (Mac OS X 10.11.5)/sorter.js' {
  declare module.exports: $Exports<'auth0-react-lock/coverage/Chrome 50.0.2661 (Mac OS X 10.11.5)/sorter'>;
}
declare module 'auth0-react-lock/env.example.js' {
  declare module.exports: $Exports<'auth0-react-lock/env.example'>;
}
declare module 'auth0-react-lock/env.js' {
  declare module.exports: $Exports<'auth0-react-lock/env'>;
}
declare module 'auth0-react-lock/src/components/lock.component.js' {
  declare module.exports: $Exports<'auth0-react-lock/src/components/lock.component'>;
}
declare module 'auth0-react-lock/src/index.js' {
  declare module.exports: $Exports<'auth0-react-lock/src/index'>;
}
declare module 'auth0-react-lock/webpack.config.js' {
  declare module.exports: $Exports<'auth0-react-lock/webpack.config'>;
}
