// flow-typed signature: eb5ff2221c3b382a81c875cc9e10187d
// flow-typed version: <<STUB>>/saul_v^0.0.17/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'saul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'saul' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'saul/flow-typed/npm/@emmetio/expand-abbreviation_vx.x.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/babylon_vx.x.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/chai_v3.5.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/enzyme_v2.3.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/flow-remove-types_vx.x.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/glob-fs_vx.x.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/mocha_v3.1.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/nyc_vx.x.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/optimist_vx.x.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/react-addons-test-utils_v15.x.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/saul_vx.x.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/sinon_vx.x.x' {
  declare module.exports: any;
}

declare module 'saul/flow-typed/npm/xregexp_vx.x.x' {
  declare module.exports: any;
}

declare module 'saul/lib/config' {
  declare module.exports: any;
}

declare module 'saul/lib/engines/calls-spy-with' {
  declare module.exports: any;
}

declare module 'saul/lib/engines/calls-spy' {
  declare module.exports: any;
}

declare module 'saul/lib/engines/contains-dom' {
  declare module.exports: any;
}

declare module 'saul/lib/engines/contains' {
  declare module.exports: any;
}

declare module 'saul/lib/engines/deep-equals' {
  declare module.exports: any;
}

declare module 'saul/lib/engines/equals' {
  declare module.exports: any;
}

declare module 'saul/lib/engines/is-not' {
  declare module.exports: any;
}

declare module 'saul/lib/engines/matches-dom' {
  declare module.exports: any;
}

declare module 'saul/lib/engines/throws' {
  declare module.exports: any;
}

declare module 'saul/lib/examples/react-examples' {
  declare module.exports: any;
}

declare module 'saul/lib/examples/simple' {
  declare module.exports: any;
}

declare module 'saul/lib/execute' {
  declare module.exports: any;
}

declare module 'saul/lib/execute.test' {
  declare module.exports: any;
}

declare module 'saul/lib/file' {
  declare module.exports: any;
}

declare module 'saul/lib/index' {
  declare module.exports: any;
}

declare module 'saul/lib/organize' {
  declare module.exports: any;
}

declare module 'saul/lib/parse' {
  declare module.exports: any;
}

declare module 'saul/lib/testcase' {
  declare module.exports: any;
}

declare module 'saul/lib/types' {
  declare module.exports: any;
}

declare module 'saul/src/config' {
  declare module.exports: any;
}

declare module 'saul/src/engines/calls-spy-with' {
  declare module.exports: any;
}

declare module 'saul/src/engines/calls-spy' {
  declare module.exports: any;
}

declare module 'saul/src/engines/contains-dom' {
  declare module.exports: any;
}

declare module 'saul/src/engines/contains' {
  declare module.exports: any;
}

declare module 'saul/src/engines/deep-equals' {
  declare module.exports: any;
}

declare module 'saul/src/engines/equals' {
  declare module.exports: any;
}

declare module 'saul/src/engines/is-not' {
  declare module.exports: any;
}

declare module 'saul/src/engines/matches-dom' {
  declare module.exports: any;
}

declare module 'saul/src/engines/throws' {
  declare module.exports: any;
}

declare module 'saul/src/examples/react-examples' {
  declare module.exports: any;
}

declare module 'saul/src/execute' {
  declare module.exports: any;
}

declare module 'saul/src/file' {
  declare module.exports: any;
}

declare module 'saul/src/index' {
  declare module.exports: any;
}

declare module 'saul/src/organize' {
  declare module.exports: any;
}

declare module 'saul/src/parse' {
  declare module.exports: any;
}

declare module 'saul/src/testcase' {
  declare module.exports: any;
}

declare module 'saul/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'saul/flow-typed/npm/@emmetio/expand-abbreviation_vx.x.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/@emmetio/expand-abbreviation_vx.x.x'>;
}
declare module 'saul/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'saul/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module 'saul/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module 'saul/flow-typed/npm/babylon_vx.x.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/babylon_vx.x.x'>;
}
declare module 'saul/flow-typed/npm/chai_v3.5.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/chai_v3.5.x'>;
}
declare module 'saul/flow-typed/npm/enzyme_v2.3.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/enzyme_v2.3.x'>;
}
declare module 'saul/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'saul/flow-typed/npm/flow-remove-types_vx.x.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/flow-remove-types_vx.x.x'>;
}
declare module 'saul/flow-typed/npm/glob-fs_vx.x.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/glob-fs_vx.x.x'>;
}
declare module 'saul/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/lodash_v4.x.x'>;
}
declare module 'saul/flow-typed/npm/mocha_v3.1.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/mocha_v3.1.x'>;
}
declare module 'saul/flow-typed/npm/nyc_vx.x.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/nyc_vx.x.x'>;
}
declare module 'saul/flow-typed/npm/optimist_vx.x.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/optimist_vx.x.x'>;
}
declare module 'saul/flow-typed/npm/react-addons-test-utils_v15.x.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/react-addons-test-utils_v15.x.x'>;
}
declare module 'saul/flow-typed/npm/saul_vx.x.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/saul_vx.x.x'>;
}
declare module 'saul/flow-typed/npm/sinon_vx.x.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/sinon_vx.x.x'>;
}
declare module 'saul/flow-typed/npm/xregexp_vx.x.x.js' {
  declare module.exports: $Exports<'saul/flow-typed/npm/xregexp_vx.x.x'>;
}
declare module 'saul/lib/config.js' {
  declare module.exports: $Exports<'saul/lib/config'>;
}
declare module 'saul/lib/engines/calls-spy-with.js' {
  declare module.exports: $Exports<'saul/lib/engines/calls-spy-with'>;
}
declare module 'saul/lib/engines/calls-spy.js' {
  declare module.exports: $Exports<'saul/lib/engines/calls-spy'>;
}
declare module 'saul/lib/engines/contains-dom.js' {
  declare module.exports: $Exports<'saul/lib/engines/contains-dom'>;
}
declare module 'saul/lib/engines/contains.js' {
  declare module.exports: $Exports<'saul/lib/engines/contains'>;
}
declare module 'saul/lib/engines/deep-equals.js' {
  declare module.exports: $Exports<'saul/lib/engines/deep-equals'>;
}
declare module 'saul/lib/engines/equals.js' {
  declare module.exports: $Exports<'saul/lib/engines/equals'>;
}
declare module 'saul/lib/engines/is-not.js' {
  declare module.exports: $Exports<'saul/lib/engines/is-not'>;
}
declare module 'saul/lib/engines/matches-dom.js' {
  declare module.exports: $Exports<'saul/lib/engines/matches-dom'>;
}
declare module 'saul/lib/engines/throws.js' {
  declare module.exports: $Exports<'saul/lib/engines/throws'>;
}
declare module 'saul/lib/examples/react-examples.js' {
  declare module.exports: $Exports<'saul/lib/examples/react-examples'>;
}
declare module 'saul/lib/examples/simple.js' {
  declare module.exports: $Exports<'saul/lib/examples/simple'>;
}
declare module 'saul/lib/execute.js' {
  declare module.exports: $Exports<'saul/lib/execute'>;
}
declare module 'saul/lib/execute.test.js' {
  declare module.exports: $Exports<'saul/lib/execute.test'>;
}
declare module 'saul/lib/file.js' {
  declare module.exports: $Exports<'saul/lib/file'>;
}
declare module 'saul/lib/index.js' {
  declare module.exports: $Exports<'saul/lib/index'>;
}
declare module 'saul/lib/organize.js' {
  declare module.exports: $Exports<'saul/lib/organize'>;
}
declare module 'saul/lib/parse.js' {
  declare module.exports: $Exports<'saul/lib/parse'>;
}
declare module 'saul/lib/testcase.js' {
  declare module.exports: $Exports<'saul/lib/testcase'>;
}
declare module 'saul/lib/types.js' {
  declare module.exports: $Exports<'saul/lib/types'>;
}
declare module 'saul/src/config.js' {
  declare module.exports: $Exports<'saul/src/config'>;
}
declare module 'saul/src/engines/calls-spy-with.js' {
  declare module.exports: $Exports<'saul/src/engines/calls-spy-with'>;
}
declare module 'saul/src/engines/calls-spy.js' {
  declare module.exports: $Exports<'saul/src/engines/calls-spy'>;
}
declare module 'saul/src/engines/contains-dom.js' {
  declare module.exports: $Exports<'saul/src/engines/contains-dom'>;
}
declare module 'saul/src/engines/contains.js' {
  declare module.exports: $Exports<'saul/src/engines/contains'>;
}
declare module 'saul/src/engines/deep-equals.js' {
  declare module.exports: $Exports<'saul/src/engines/deep-equals'>;
}
declare module 'saul/src/engines/equals.js' {
  declare module.exports: $Exports<'saul/src/engines/equals'>;
}
declare module 'saul/src/engines/is-not.js' {
  declare module.exports: $Exports<'saul/src/engines/is-not'>;
}
declare module 'saul/src/engines/matches-dom.js' {
  declare module.exports: $Exports<'saul/src/engines/matches-dom'>;
}
declare module 'saul/src/engines/throws.js' {
  declare module.exports: $Exports<'saul/src/engines/throws'>;
}
declare module 'saul/src/examples/react-examples.js' {
  declare module.exports: $Exports<'saul/src/examples/react-examples'>;
}
declare module 'saul/src/execute.js' {
  declare module.exports: $Exports<'saul/src/execute'>;
}
declare module 'saul/src/file.js' {
  declare module.exports: $Exports<'saul/src/file'>;
}
declare module 'saul/src/index.js' {
  declare module.exports: $Exports<'saul/src/index'>;
}
declare module 'saul/src/organize.js' {
  declare module.exports: $Exports<'saul/src/organize'>;
}
declare module 'saul/src/parse.js' {
  declare module.exports: $Exports<'saul/src/parse'>;
}
declare module 'saul/src/testcase.js' {
  declare module.exports: $Exports<'saul/src/testcase'>;
}
declare module 'saul/src/types.js' {
  declare module.exports: $Exports<'saul/src/types'>;
}
