/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule createPluginMutation.graphql
 * @generated SignedSource<<2b3a51793b51b3d31287ba27c42699bf>>
 * @relayHash 24f1a1e504585685bab932b84dbc4556
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
mutation createPluginMutation(
  $plugin: CreatePluginInput!
) {
  createPlugin(plugin: $plugin)
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "plugin",
        "type": "CreatePluginInput!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "createPluginMutation",
    "selections": [
      {
        "kind": "ScalarField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "plugin",
            "variableName": "plugin",
            "type": "CreatePluginInput!"
          }
        ],
        "name": "createPlugin",
        "storageKey": null
      }
    ],
    "type": "Mutation"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "createPluginMutation",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "plugin",
        "type": "CreatePluginInput!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "createPluginMutation",
    "operation": "mutation",
    "selections": [
      {
        "kind": "ScalarField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "plugin",
            "variableName": "plugin",
            "type": "CreatePluginInput!"
          }
        ],
        "name": "createPlugin",
        "storageKey": null
      }
    ]
  },
  "text": "mutation createPluginMutation(\n  $plugin: CreatePluginInput!\n) {\n  createPlugin(plugin: $plugin)\n}\n"
};

module.exports = batch;
