/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule HealthCheckQuery.graphql
 * @generated SignedSource<<b93e3057c1aaf9ee0d0533e9c41a77d4>>
 * @relayHash 3c9cfc9e14f5e0cae4a9faeaab2d4d33
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query HealthCheckQuery {
  checkHealth {
    healthy
    message
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "HealthCheckQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "HealthStatus",
        "name": "checkHealth",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "healthy",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "message",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "HealthCheckQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "HealthCheckQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "HealthStatus",
        "name": "checkHealth",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "healthy",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "message",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query HealthCheckQuery {\n  checkHealth {\n    healthy\n    message\n  }\n}\n"
};

module.exports = batch;
